#' @title Instantiate an Explainer
#'
#' @details \code{instantiate_explainer} is a polymorphism function.
#'
#' @param object (`train`) A caret model generated by \link[caret]{train}.
#'
#' @return (`Explanations`) An explainer object that has public methods for
#'   explaining \code{object}.
#'
#' @export
instantiate_explainer <- function(object){
    object %>%
        CaretModelDecomposition$new() %>%
        ModelComposition$new() %>%
        Explanations$new()
}
